/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as PraticienRouteImport } from './routes/praticien'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCalendrierRouteImport } from './routes/admin.calendrier'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminDisponibilitesRouteImport } from './routes/admin.disponibilites'
import { Route as AdminPaiementsRouteImport } from './routes/admin.paiements'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminPraticiensRouteImport } from './routes/admin.praticiens'
import { Route as AdminPrestationsRouteImport } from './routes/admin.prestations'
import { Route as AdminRendezVousRouteImport } from './routes/admin.rendez-vous'
import { Route as PraticienIndexRouteImport } from './routes/praticien.index'
import { Route as PraticienCalendrierRouteImport } from './routes/praticien.calendrier'
import { Route as PraticienClientsRouteImport } from './routes/praticien.clients'
import { Route as PraticienDisponibilitesRouteImport } from './routes/praticien.disponibilites'
import { Route as PraticienRendezVousRouteImport } from './routes/praticien.rendez-vous'
import { Route as SoinsIndexRouteImport } from './routes/soins.index'
import { Route as SoinsSlugRouteImport } from './routes/soins.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const PraticienRoute = PraticienRouteImport.update({
  id: '/praticien',
  path: '/praticien',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendrierRoute = AdminCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisponibilitesRoute = AdminDisponibilitesRouteImport.update({
  id: '/disponibilites',
  path: '/disponibilites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPraticiensRoute = AdminPraticiensRouteImport.update({
  id: '/praticiens',
  path: '/praticiens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrestationsRoute = AdminPrestationsRouteImport.update({
  id: '/prestations',
  path: '/prestations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRendezVousRoute = AdminRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => AdminRoute,
} as any)
const PraticienIndexRoute = PraticienIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PraticienRoute,
} as any)
const PraticienCalendrierRoute = PraticienCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => PraticienRoute,
} as any)
const PraticienClientsRoute = PraticienClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => PraticienRoute,
} as any)
const PraticienDisponibilitesRoute = PraticienDisponibilitesRouteImport.update({
  id: '/disponibilites',
  path: '/disponibilites',
  getParentRoute: () => PraticienRoute,
} as any)
const PraticienRendezVousRoute = PraticienRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => PraticienRoute,
} as any)
const SoinsIndexRoute = SoinsIndexRouteImport.update({
  id: '/soins/',
  path: '/soins/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoinsSlugRoute = SoinsSlugRouteImport.update({
  id: '/soins/$slug',
  path: '/soins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/compte': typeof CompteRoute
  '/confirmation': typeof ConfirmationRoute
  '/connexion': typeof ConnexionRoute
  '/paiement': typeof PaiementRoute
  '/praticien': typeof PraticienRouteWithChildren
  '/reservation': typeof ReservationRoute
  '/admin/calendrier': typeof AdminCalendrierRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/disponibilites': typeof AdminDisponibilitesRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/praticiens': typeof AdminPraticiensRoute
  '/admin/prestations': typeof AdminPrestationsRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/praticien/calendrier': typeof PraticienCalendrierRoute
  '/praticien/clients': typeof PraticienClientsRoute
  '/praticien/disponibilites': typeof PraticienDisponibilitesRoute
  '/praticien/rendez-vous': typeof PraticienRendezVousRoute
  '/soins/$slug': typeof SoinsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/praticien/': typeof PraticienIndexRoute
  '/soins/': typeof SoinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compte': typeof CompteRoute
  '/confirmation': typeof ConfirmationRoute
  '/connexion': typeof ConnexionRoute
  '/paiement': typeof PaiementRoute
  '/reservation': typeof ReservationRoute
  '/admin/calendrier': typeof AdminCalendrierRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/disponibilites': typeof AdminDisponibilitesRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/praticiens': typeof AdminPraticiensRoute
  '/admin/prestations': typeof AdminPrestationsRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/praticien/calendrier': typeof PraticienCalendrierRoute
  '/praticien/clients': typeof PraticienClientsRoute
  '/praticien/disponibilites': typeof PraticienDisponibilitesRoute
  '/praticien/rendez-vous': typeof PraticienRendezVousRoute
  '/soins/$slug': typeof SoinsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/praticien': typeof PraticienIndexRoute
  '/soins': typeof SoinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/compte': typeof CompteRoute
  '/confirmation': typeof ConfirmationRoute
  '/connexion': typeof ConnexionRoute
  '/paiement': typeof PaiementRoute
  '/praticien': typeof PraticienRouteWithChildren
  '/reservation': typeof ReservationRoute
  '/admin/calendrier': typeof AdminCalendrierRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/disponibilites': typeof AdminDisponibilitesRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/praticiens': typeof AdminPraticiensRoute
  '/admin/prestations': typeof AdminPrestationsRoute
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/praticien/calendrier': typeof PraticienCalendrierRoute
  '/praticien/clients': typeof PraticienClientsRoute
  '/praticien/disponibilites': typeof PraticienDisponibilitesRoute
  '/praticien/rendez-vous': typeof PraticienRendezVousRoute
  '/soins/$slug': typeof SoinsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/praticien/': typeof PraticienIndexRoute
  '/soins/': typeof SoinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/compte'
    | '/confirmation'
    | '/connexion'
    | '/paiement'
    | '/praticien'
    | '/reservation'
    | '/admin/calendrier'
    | '/admin/clients'
    | '/admin/disponibilites'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/praticiens'
    | '/admin/prestations'
    | '/admin/rendez-vous'
    | '/praticien/calendrier'
    | '/praticien/clients'
    | '/praticien/disponibilites'
    | '/praticien/rendez-vous'
    | '/soins/$slug'
    | '/admin/'
    | '/praticien/'
    | '/soins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compte'
    | '/confirmation'
    | '/connexion'
    | '/paiement'
    | '/reservation'
    | '/admin/calendrier'
    | '/admin/clients'
    | '/admin/disponibilites'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/praticiens'
    | '/admin/prestations'
    | '/admin/rendez-vous'
    | '/praticien/calendrier'
    | '/praticien/clients'
    | '/praticien/disponibilites'
    | '/praticien/rendez-vous'
    | '/soins/$slug'
    | '/admin'
    | '/praticien'
    | '/soins'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/compte'
    | '/confirmation'
    | '/connexion'
    | '/paiement'
    | '/praticien'
    | '/reservation'
    | '/admin/calendrier'
    | '/admin/clients'
    | '/admin/disponibilites'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/praticiens'
    | '/admin/prestations'
    | '/admin/rendez-vous'
    | '/praticien/calendrier'
    | '/praticien/clients'
    | '/praticien/disponibilites'
    | '/praticien/rendez-vous'
    | '/soins/$slug'
    | '/admin/'
    | '/praticien/'
    | '/soins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompteRoute: typeof CompteRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ConnexionRoute: typeof ConnexionRoute
  PaiementRoute: typeof PaiementRoute
  PraticienRoute: typeof PraticienRouteWithChildren
  ReservationRoute: typeof ReservationRoute
  SoinsSlugRoute: typeof SoinsSlugRoute
  SoinsIndexRoute: typeof SoinsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praticien': {
      id: '/praticien'
      path: '/praticien'
      fullPath: '/praticien'
      preLoaderRoute: typeof PraticienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendrier': {
      id: '/admin/calendrier'
      path: '/calendrier'
      fullPath: '/admin/calendrier'
      preLoaderRoute: typeof AdminCalendrierRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disponibilites': {
      id: '/admin/disponibilites'
      path: '/disponibilites'
      fullPath: '/admin/disponibilites'
      preLoaderRoute: typeof AdminDisponibilitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/praticiens': {
      id: '/admin/praticiens'
      path: '/praticiens'
      fullPath: '/admin/praticiens'
      preLoaderRoute: typeof AdminPraticiensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prestations': {
      id: '/admin/prestations'
      path: '/prestations'
      fullPath: '/admin/prestations'
      preLoaderRoute: typeof AdminPrestationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rendez-vous': {
      id: '/admin/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/admin/rendez-vous'
      preLoaderRoute: typeof AdminRendezVousRouteImport
      parentRoute: typeof AdminRoute
    }
    '/praticien/': {
      id: '/praticien/'
      path: '/'
      fullPath: '/praticien/'
      preLoaderRoute: typeof PraticienIndexRouteImport
      parentRoute: typeof PraticienRoute
    }
    '/praticien/calendrier': {
      id: '/praticien/calendrier'
      path: '/calendrier'
      fullPath: '/praticien/calendrier'
      preLoaderRoute: typeof PraticienCalendrierRouteImport
      parentRoute: typeof PraticienRoute
    }
    '/praticien/clients': {
      id: '/praticien/clients'
      path: '/clients'
      fullPath: '/praticien/clients'
      preLoaderRoute: typeof PraticienClientsRouteImport
      parentRoute: typeof PraticienRoute
    }
    '/praticien/disponibilites': {
      id: '/praticien/disponibilites'
      path: '/disponibilites'
      fullPath: '/praticien/disponibilites'
      preLoaderRoute: typeof PraticienDisponibilitesRouteImport
      parentRoute: typeof PraticienRoute
    }
    '/praticien/rendez-vous': {
      id: '/praticien/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/praticien/rendez-vous'
      preLoaderRoute: typeof PraticienRendezVousRouteImport
      parentRoute: typeof PraticienRoute
    }
    '/soins/': {
      id: '/soins/'
      path: '/soins'
      fullPath: '/soins/'
      preLoaderRoute: typeof SoinsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soins/$slug': {
      id: '/soins/$slug'
      path: '/soins/$slug'
      fullPath: '/soins/$slug'
      preLoaderRoute: typeof SoinsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCalendrierRoute: typeof AdminCalendrierRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDisponibilitesRoute: typeof AdminDisponibilitesRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminPraticiensRoute: typeof AdminPraticiensRoute
  AdminPrestationsRoute: typeof AdminPrestationsRoute
  AdminRendezVousRoute: typeof AdminRendezVousRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendrierRoute: AdminCalendrierRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDisponibilitesRoute: AdminDisponibilitesRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminPraticiensRoute: AdminPraticiensRoute,
  AdminPrestationsRoute: AdminPrestationsRoute,
  AdminRendezVousRoute: AdminRendezVousRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PraticienRouteChildren {
  PraticienCalendrierRoute: typeof PraticienCalendrierRoute
  PraticienClientsRoute: typeof PraticienClientsRoute
  PraticienDisponibilitesRoute: typeof PraticienDisponibilitesRoute
  PraticienRendezVousRoute: typeof PraticienRendezVousRoute
  PraticienIndexRoute: typeof PraticienIndexRoute
}

const PraticienRouteChildren: PraticienRouteChildren = {
  PraticienCalendrierRoute: PraticienCalendrierRoute,
  PraticienClientsRoute: PraticienClientsRoute,
  PraticienDisponibilitesRoute: PraticienDisponibilitesRoute,
  PraticienRendezVousRoute: PraticienRendezVousRoute,
  PraticienIndexRoute: PraticienIndexRoute,
}

const PraticienRouteWithChildren = PraticienRoute._addFileChildren(
  PraticienRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CompteRoute: CompteRoute,
  ConfirmationRoute: ConfirmationRoute,
  ConnexionRoute: ConnexionRoute,
  PaiementRoute: PaiementRoute,
  PraticienRoute: PraticienRouteWithChildren,
  ReservationRoute: ReservationRoute,
  SoinsSlugRoute: SoinsSlugRoute,
  SoinsIndexRoute: SoinsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
